[package]
name = "ferium"
version = "4.4.0"
edition = "2021"
rust-version = "1.61" # Bound by `std::process::ExitCode`
authors = [
    "Ilesh Thiada (theRookieCoder) <ileshkt@gmail.com>",
    "薛詠謙 (KyleUltimate)",
    "Daniel Hauck (SolidTux)",
]
description = "Fast CLI program for managing Minecraft mods and modpacks from Modrinth, CurseForge, and Github Releases"
exclude = [
    "tests",
    "media",
] # Don't need tests and media for installing using crates.io
repository = "https://github.com/gorilla-devs/ferium"
categories = ["command-line-utilities"]
readme = "README.md"
license = "MPL-2.0"
keywords = ["minecraft", "mod-manager", "modrinth", "curseforge", "github"]

[features]
default = ["gui"]
gui = ["libium/gui"]

[dependencies]
octocrab = { version = "0.18", default-features = false, features = ["rustls"] }
reqwest = { version = "0.11", default-features = false, features = [
    "rustls-tls",
] }
online = { version = "4.0", default-features = false, features = [
    "tokio-runtime",
] }
tokio = { version = "1.26", default-features = false, features = [
    "rt-multi-thread",
    "macros",
] }
clap = { version = "4.1", features = ["derive"] }
clap_complete = "4.1"
serde_json = "1.0"
dialoguer = "0.10"
indicatif = "0.17"
itertools = "0.10"
once_cell = "1.17"
fs_extra = "1.3"
colored = "2.0"
ferinth = "2.7"
# libium = "1.23"
libium = { git = "https://github.com/gorilla-devs/libium.git" }
anyhow = "1.0"
semver = "1.0"
bytes = "1.1"
furse = "1.5"
sha1 = "0.10"
sha2 = "0.10"
size = "0.4"
url = "2.3"

[dev-dependencies]
rand = "0.8"

[profile.release]
codegen-units = 1
strip = true
lto = true
